/*
 * Copyright 2017 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.bc.appbase.ui;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Josh
 */
public class LogPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogPanel
     */
    public LogPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();

        messageTextArea.setEditable(false);
        messageTextArea.setBackground(new java.awt.Color(51, 0, 204));
        messageTextArea.setColumns(20);
        messageTextArea.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        messageTextArea.setForeground(new java.awt.Color(255, 255, 255));
        messageTextArea.setRows(5);
        messageTextArea.setBorder(null);
        messageTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        messageTextArea.setDoubleBuffered(true);
        messageTextArea.setSelectionColor(new java.awt.Color(204, 255, 255));
        scrollPane.setViewportView(messageTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    public JTextArea getMessageTextArea() {
        return messageTextArea;
    }

    public JScrollPane getScrollPane() {
        return scrollPane;
    }
}
