/*
 * Copyright 2017 NUROX Ltd.
 *
 * Licensed under the NUROX Ltd Software License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.looseboxes.com/legal/licenses/software.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.bc.appbase.ui;

import com.bc.jpa.search.SearchResults;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import com.bc.appbase.App;
import com.bc.appcore.jpa.SearchContext;
import com.bc.appbase.ui.actions.ActionCommands;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Josh
 */
public class SearchResultsPanel extends javax.swing.JPanel {

    public SearchResultsPanel() {
        this(null);
    }
    
    public SearchResultsPanel(App app) {
        initComponents();
        if(app != null) {
            this.init(app);
        }
    }

    public void init(App app) {
        
        final JTable table = this.getSearchResultsTable();
        
        final Font font = app.getUIContext().getFont(table);
        table.setFont(font);
        table.getTableHeader().setFont(font.deriveFont(Font.BOLD));
//        table.setIntercellSpacing(new Dimension(4, 4));
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        table.setShowGrid(true);
        table.setGridColor(Color.DARK_GRAY);

        table.setAutoCreateRowSorter(true);

        this.getNextPageButton().setActionCommand(ActionCommands.NEXT_RESULT);
        this.getPreviousPageButton().setActionCommand(ActionCommands.PREVIOUS_RESULT);
        this.getLastPageButton().setActionCommand(ActionCommands.LAST_RESULT);
        this.getFirstPageButton().setActionCommand(ActionCommands.FIRST_RESULT);
        
        app.getUIContext().addActionListeners(table, this.getAddButton(),
                this.getNextPageButton(), this.getPreviousPageButton(),
                this.getLastPageButton(), this.getFirstPageButton());

        table.addMouseListener(app.getUIContext().getMouseListener(this));
    }

    public void reset(App app, Class entityType) {
        
        final SearchResults searchResults = app.getUIContext().getLinkedSearchResults(this);
        
        if(searchResults != null) {
            this.reset(app, entityType, searchResults);
        }
    }
    
    public <T> void reset(App app, Class<T> entityType, SearchResults<T> searchResults) {
        
        final SearchContext<T> searchContext = app.getSearchContext(entityType);
        
        this.reset(app, searchContext, searchResults);
    }
    
    public void reset(App app, SearchContext searchContext, SearchResults searchResults) {
        
        Objects.requireNonNull(app);
        Objects.requireNonNull(searchContext);
        Objects.requireNonNull(searchResults);
        
        final String KEY = this.getName();
        
        final SearchResults previous = (SearchResults)app.getAttributes().get(KEY);
        if(previous instanceof AutoCloseable && !previous.equals(searchResults)) {
            try{
                ((AutoCloseable)previous).close();
            }catch(Exception e) {
                Logger.getLogger(this.getClass().getName()).log(
                        Level.WARNING, "Error closing search results table", e);
            }
        }
        
        app.getUIContext().loadSearchResultsUI(
                this, searchContext, searchResults, KEY, 0, 1, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable();
        previousPageButton = new javax.swing.JButton();
        nextPageButton = new javax.swing.JButton();
        paginationLabel = new javax.swing.JLabel();
        firstPageButton = new javax.swing.JButton();
        lastPageButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setPreferredSize(new java.awt.Dimension(570, 512));

        scrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        searchResultsTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        searchResultsTable.setMaximumSize(new java.awt.Dimension(32767, 32767));
        searchResultsTable.setPreferredSize(new java.awt.Dimension(600, 500));
        scrollPane.setViewportView(searchResultsTable);

        previousPageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        previousPageButton.setText("<");

        nextPageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nextPageButton.setText(">");

        paginationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paginationLabel.setPreferredSize(new java.awt.Dimension(186, 31));

        firstPageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstPageButton.setText("<<");

        lastPageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lastPageButton.setText(">>");

        addButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addButton.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstPageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousPageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paginationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextPageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastPageButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextPageButton)
                            .addComponent(lastPageButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousPageButton)
                            .addComponent(firstPageButton)
                            .addComponent(addButton)))
                    .addComponent(paginationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton firstPageButton;
    private javax.swing.JButton lastPageButton;
    private javax.swing.JButton nextPageButton;
    private javax.swing.JLabel paginationLabel;
    private javax.swing.JButton previousPageButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable searchResultsTable;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getScrollPane() {
        return scrollPane;
    }

    public JTable getSearchResultsTable() {
        return searchResultsTable;
    }

    public JButton getNextPageButton() {
        return nextPageButton;
    }

    public JLabel getPaginationLabel() {
        return paginationLabel;
    }

    public JButton getPreviousPageButton() {
        return previousPageButton;
    }

    public JButton getFirstPageButton() {
        return firstPageButton;
    }

    public JButton getLastPageButton() {
        return lastPageButton;
    }

    public JButton getAddButton() {
        return addButton;
    }
}
